import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export default function Homepage() {
  return (
    <>
      <Head>
        <title>Example #1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to my page</h1>

        <ul>
          <li>
            Create
          </li>
          <li>
            Read
          </li>
          <li>
            Update
          </li>
          <li>
            Delete
          </li>
        </ul>

        <button>View all this info</button>

      <nav>
        <Link href="/about">About Page</Link>
        <br/>
        <Link href="/grades">Grades Page</Link>
      </nav>
      </main>
      
      <footer>In Class Example #1</footer>

    </>
  )
}
